CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Boards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "OwnerId" integer NOT NULL,
    CONSTRAINT "PK_Boards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Boards_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BoardMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JoinedAt" timestamp with time zone NOT NULL,
    "Role" text NOT NULL,
    "UserId" integer NOT NULL,
    "BoardId" integer NOT NULL,
    CONSTRAINT "PK_BoardMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BoardMembers_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id"),
    CONSTRAINT "FK_BoardMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Columns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Order" integer NOT NULL,
    "BoardId" integer NOT NULL,
    CONSTRAINT "PK_Columns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Columns_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskCards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ColumnId" integer NOT NULL,
    CONSTRAINT "PK_TaskCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskCards_Columns_ColumnId" FOREIGN KEY ("ColumnId") REFERENCES "Columns" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BoardMembers_BoardId" ON "BoardMembers" ("BoardId");

CREATE UNIQUE INDEX "IX_BoardMembers_UserId_BoardId" ON "BoardMembers" ("UserId", "BoardId");

CREATE INDEX "IX_Boards_OwnerId" ON "Boards" ("OwnerId");

CREATE INDEX "IX_Columns_BoardId" ON "Columns" ("BoardId");

CREATE INDEX "IX_TaskCards_ColumnId" ON "TaskCards" ("ColumnId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216165215_AddBoardMembers', '9.0.13');

ALTER TABLE "BoardMembers" ADD "Status" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216180103_AddInvitationWorkflow', '9.0.13');

ALTER TABLE "TaskCards" ADD "AssigneeId" integer;

ALTER TABLE "TaskCards" ADD "DueDate" timestamp with time zone;

ALTER TABLE "TaskCards" ADD "Priority" text NOT NULL DEFAULT '';

ALTER TABLE "TaskCards" ADD "StoryPoints" integer;

ALTER TABLE "TaskCards" ADD "Tags" text;

CREATE INDEX "IX_TaskCards_AssigneeId" ON "TaskCards" ("AssigneeId");

ALTER TABLE "TaskCards" ADD CONSTRAINT "FK_TaskCards_Users_AssigneeId" FOREIGN KEY ("AssigneeId") REFERENCES "Users" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216180550_AddScrumFields', '9.0.13');

ALTER TABLE "Boards" ADD "BackgroundImageUrl" text;

ALTER TABLE "Boards" ADD "IsPrivate" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Boards" ADD "ThemeColor" text NOT NULL DEFAULT '';

ALTER TABLE "Boards" ADD "WorkspaceId" integer;

CREATE TABLE "Workspaces" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "OwnerId" integer NOT NULL,
    CONSTRAINT "PK_Workspaces" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Workspaces_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "WorkspaceMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JoinedAt" timestamp with time zone NOT NULL,
    "Role" text NOT NULL,
    "WorkspaceId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_WorkspaceMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkspaceMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkspaceMembers_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES "Workspaces" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Boards_WorkspaceId" ON "Boards" ("WorkspaceId");

CREATE UNIQUE INDEX "IX_WorkspaceMembers_UserId_WorkspaceId" ON "WorkspaceMembers" ("UserId", "WorkspaceId");

CREATE INDEX "IX_WorkspaceMembers_WorkspaceId" ON "WorkspaceMembers" ("WorkspaceId");

CREATE INDEX "IX_Workspaces_OwnerId" ON "Workspaces" ("OwnerId");

ALTER TABLE "Boards" ADD CONSTRAINT "FK_Boards_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES "Workspaces" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217191752_AddWorkspacesAndThemesFix', '9.0.13');

ALTER TABLE "WorkspaceMembers" ADD "Status" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217203741_AddWorkspaceMemberStatus', '9.0.13');

CREATE TABLE "Subtasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "TaskCardId" integer NOT NULL,
    CONSTRAINT "PK_Subtasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subtasks_TaskCards_TaskCardId" FOREIGN KEY ("TaskCardId") REFERENCES "TaskCards" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Subtasks_TaskCardId" ON "Subtasks" ("TaskCardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260218222535_AddSubtasks', '9.0.13');

CREATE TABLE "TaskActivities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskCardId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Action" text NOT NULL,
    "Details" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskActivities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskActivities_TaskCards_TaskCardId" FOREIGN KEY ("TaskCardId") REFERENCES "TaskCards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskActivities_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskActivities_TaskCardId" ON "TaskActivities" ("TaskCardId");

CREATE INDEX "IX_TaskActivities_UserId" ON "TaskActivities" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219005358_AddActivityLog', '9.0.13');

ALTER TABLE "Users" ADD "AvatarUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219155014_AddAvatarUrlToUser', '9.0.13');

CREATE TABLE "TimeLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskCardId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "StoppedAt" timestamp with time zone,
    "DurationMinutes" integer,
    CONSTRAINT "PK_TimeLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TimeLogs_TaskCards_TaskCardId" FOREIGN KEY ("TaskCardId") REFERENCES "TaskCards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TimeLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TimeLogs_TaskCardId" ON "TimeLogs" ("TaskCardId");

CREATE INDEX "IX_TimeLogs_UserId" ON "TimeLogs" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219224142_SyncModels', '9.0.13');

CREATE TABLE "Attachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskCardId" integer NOT NULL,
    "UploadedById" integer NOT NULL,
    "FileName" text NOT NULL,
    "StoragePath" text NOT NULL,
    "PublicUrl" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Attachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attachments_TaskCards_TaskCardId" FOREIGN KEY ("TaskCardId") REFERENCES "TaskCards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Attachments_Users_UploadedById" FOREIGN KEY ("UploadedById") REFERENCES "Users" ("Id")
);

CREATE TABLE "TaskAssignees" (
    "TaskCardId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_TaskAssignees" PRIMARY KEY ("TaskCardId", "UserId"),
    CONSTRAINT "FK_TaskAssignees_TaskCards_TaskCardId" FOREIGN KEY ("TaskCardId") REFERENCES "TaskCards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskAssignees_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_Attachments_TaskCardId" ON "Attachments" ("TaskCardId");

CREATE INDEX "IX_Attachments_UploadedById" ON "Attachments" ("UploadedById");

CREATE INDEX "IX_TaskAssignees_UserId" ON "TaskAssignees" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260221145333_AddAttachmentsAndMultiAssignees', '9.0.13');

CREATE TABLE "Labels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Color" text NOT NULL,
    "BoardId" integer NOT NULL,
    CONSTRAINT "PK_Labels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Labels_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskLabels" (
    "TaskCardId" integer NOT NULL,
    "LabelId" integer NOT NULL,
    CONSTRAINT "PK_TaskLabels" PRIMARY KEY ("TaskCardId", "LabelId"),
    CONSTRAINT "FK_TaskLabels_Labels_LabelId" FOREIGN KEY ("LabelId") REFERENCES "Labels" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskLabels_TaskCards_TaskCardId" FOREIGN KEY ("TaskCardId") REFERENCES "TaskCards" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Labels_BoardId" ON "Labels" ("BoardId");

CREATE INDEX "IX_TaskLabels_LabelId" ON "TaskLabels" ("LabelId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222145134_AddLabels', '9.0.13');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222151942_AnalyticsOptimization', '9.0.13');

ALTER TABLE "Users" ADD "ThemePreference" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222153352_AddThemePreference', '9.0.13');

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "RelatedId" integer,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222231234_AddNotificationTable', '9.0.13');

CREATE TABLE "TaskActivityReactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskActivityId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Emoji" text NOT NULL,
    CONSTRAINT "PK_TaskActivityReactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskActivityReactions_TaskActivities_TaskActivityId" FOREIGN KEY ("TaskActivityId") REFERENCES "TaskActivities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskActivityReactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskActivityReactions_TaskActivityId" ON "TaskActivityReactions" ("TaskActivityId");

CREATE INDEX "IX_TaskActivityReactions_UserId" ON "TaskActivityReactions" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260223224513_AddCommentReactions', '9.0.13');

ALTER TABLE "Boards" ADD "IsClosed" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224153010_AddBoardIsClosed', '9.0.13');

ALTER TABLE "Users" ADD "OpenRouterApiKey" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224193245_AddOpenRouterApiKeyToUser', '9.0.13');

ALTER TABLE "TaskCards" ADD "ErDiagramPuml" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224212340_AddErDiagramToTaskCard', '9.0.13');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225005553_AddActivityIndexes', '9.0.13');

CREATE TABLE "BoardInvites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "Role" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "BoardId" integer NOT NULL,
    "CreatorId" integer NOT NULL,
    CONSTRAINT "PK_BoardInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BoardInvites_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BoardInvites_Users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_BoardInvites_BoardId" ON "BoardInvites" ("BoardId");

CREATE INDEX "IX_BoardInvites_CreatorId" ON "BoardInvites" ("CreatorId");

CREATE UNIQUE INDEX "IX_BoardInvites_Token" ON "BoardInvites" ("Token");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225153001_AddBoardInvites', '9.0.13');

CREATE TABLE "WorkspaceInvites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "Role" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "WorkspaceId" integer NOT NULL,
    "CreatorId" integer NOT NULL,
    CONSTRAINT "PK_WorkspaceInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkspaceInvites_Users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WorkspaceInvites_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES "Workspaces" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorkspaceInvites_CreatorId" ON "WorkspaceInvites" ("CreatorId");

CREATE UNIQUE INDEX "IX_WorkspaceInvites_Token" ON "WorkspaceInvites" ("Token");

CREATE INDEX "IX_WorkspaceInvites_WorkspaceId" ON "WorkspaceInvites" ("WorkspaceId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225175153_AddWorkspaceInvites', '9.0.13');

ALTER TABLE "Users" ADD "DisplayOfflineAlways" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226214030_AddUserDisplayOfflineAlways', '9.0.13');

CREATE TABLE "BoardAutomations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BoardId" integer NOT NULL,
    "TriggerType" text NOT NULL,
    "TriggerCondition" text NOT NULL,
    "ActionType" text NOT NULL,
    "ActionValue" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BoardAutomations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BoardAutomations_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BoardAutomations_BoardId" ON "BoardAutomations" ("BoardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226221934_AddBoardAutomations', '9.0.13');

DELETE FROM "Boards" WHERE "WorkspaceId" IS NULL;

UPDATE "Boards" SET "WorkspaceId" = 0 WHERE "WorkspaceId" IS NULL;
ALTER TABLE "Boards" ALTER COLUMN "WorkspaceId" SET NOT NULL;
ALTER TABLE "Boards" ALTER COLUMN "WorkspaceId" SET DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227011814_MandateWorkspaceForBoards', '9.0.13');

ALTER TABLE "Users" ADD "FullName" text;

ALTER TABLE "Users" ADD "JobTitle" text;

ALTER TABLE "Users" ADD "Department" text;

ALTER TABLE "Users" ADD "Location" text;

ALTER TABLE "Users" ADD "Organization" text;

ALTER TABLE "Users" ADD "Bio" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227044442_AddMissingUserFields', '9.0.13');

ALTER TABLE "Workspaces" ADD "LogoUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260303022339_AddWorkspaceLogoFinal', '9.0.13');

COMMIT;

